# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ram_32x256/ram_32x256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_32x256 || ORIG_REF_NAME==ram_32x256} -quiet] -quiet

# IP: ip/n_ram7x365/n_ram7x365.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n_ram7x365 || ORIG_REF_NAME==n_ram7x365} -quiet] -quiet

# IP: ip/c_ram8x365/c_ram8x365.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_ram8x365 || ORIG_REF_NAME==c_ram8x365} -quiet] -quiet

# IP: ip/b_ram9x365/b_ram9x365.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_ram9x365 || ORIG_REF_NAME==b_ram9x365} -quiet] -quiet

# IP: ip/a_ram13x365/a_ram13x365.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==a_ram13x365 || ORIG_REF_NAME==a_ram13x365} -quiet] -quiet

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_0_1 || ORIG_REF_NAME==system_axi_dma_0_1} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_1_0/system_ps7_0_axi_periph_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_1_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_apb_bridge_0_0/system_axi_apb_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_apb_bridge_0_0 || ORIG_REF_NAME==system_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_apb_reg_0_1/system_apb_reg_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_apb_reg_0_1 || ORIG_REF_NAME==system_apb_reg_0_1} -quiet] -quiet

# IP: bd/system/ip/system_encoder_top_0_0/system_encoder_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_encoder_top_0_0 || ORIG_REF_NAME==system_encoder_top_0_0} -quiet] -quiet

# IP: ip/ram_32x256/ram_32x256.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_32x256 || ORIG_REF_NAME==ram_32x256} -quiet] -quiet

# IP: ip/n_ram7x365/n_ram7x365.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n_ram7x365 || ORIG_REF_NAME==n_ram7x365} -quiet] -quiet

# IP: ip/c_ram8x365/c_ram8x365.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_ram8x365 || ORIG_REF_NAME==c_ram8x365} -quiet] -quiet

# IP: ip/b_ram9x365/b_ram9x365.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_ram9x365 || ORIG_REF_NAME==b_ram9x365} -quiet] -quiet

# IP: ip/a_ram13x365/a_ram13x365.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==a_ram13x365 || ORIG_REF_NAME==a_ram13x365} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_2/system_axi_smc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_smc_2 || ORIG_REF_NAME==system_axi_smc_2} -quiet] -quiet

# Block Designs: bd/system/ip/system_axi_smc_2/bd_0/bd_8562.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_0/bd_8562_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_1/bd_8562_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_2/bd_8562_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_3/bd_8562_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_4/bd_8562_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_5/bd_8562_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_6/bd_8562_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_7/bd_8562_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_8/bd_8562_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_9/bd_8562_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_10/bd_8562_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_11/bd_8562_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_12/bd_8562_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_13/bd_8562_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_14/bd_8562_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_15/bd_8562_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_16/bd_8562_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_17/bd_8562_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_18/bd_8562_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_19/bd_8562_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_20/bd_8562_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_21/bd_8562_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_22/bd_8562_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_23/bd_8562_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_24/bd_8562_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_25/bd_8562_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_26/bd_8562_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_27/bd_8562_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_28/bd_8562_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_29/bd_8562_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_30/bd_8562_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_31/bd_8562_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_32/bd_8562_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_33/bd_8562_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_34/bd_8562_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_35/bd_8562_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_36/bd_8562_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_37/bd_8562_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_38/bd_8562_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_39/bd_8562_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_40/bd_8562_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_41/bd_8562_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_42/bd_8562_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_rst_ps7_0_10M_0/system_rst_ps7_0_10M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_10M_0 || ORIG_REF_NAME==system_rst_ps7_0_10M_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: ip/ram_32x256/ram_32x256_ooc.xdc

# XDC: ip/n_ram7x365/n_ram7x365_ooc.xdc

# XDC: ip/c_ram8x365/c_ram8x365_ooc.xdc

# XDC: ip/b_ram9x365/b_ram9x365_ooc.xdc

# XDC: ip/a_ram13x365/a_ram13x365_ooc.xdc

# XDC: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1_ooc.xdc

# XDC: bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_0_1 || ORIG_REF_NAME==system_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_0_1 || ORIG_REF_NAME==system_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_apb_bridge_0_0/system_axi_apb_bridge_0_0_ooc.xdc

# XDC: ip/ram_32x256/ram_32x256_ooc.xdc

# XDC: ip/n_ram7x365/n_ram7x365_ooc.xdc

# XDC: ip/c_ram8x365/c_ram8x365_ooc.xdc

# XDC: ip/b_ram9x365/b_ram9x365_ooc.xdc

# XDC: ip/a_ram13x365/a_ram13x365_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_1/bd_8562_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_1/bd_8562_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_2/bd_8562_arsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_3/bd_8562_rsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_4/bd_8562_awsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_5/bd_8562_wsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_6/bd_8562_bsw_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_10/bd_8562_s00a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_11/bd_8562_sarn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_12/bd_8562_srn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_13/bd_8562_sawn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_14/bd_8562_swn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_15/bd_8562_sbn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_19/bd_8562_s01a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_20/bd_8562_sarn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_21/bd_8562_srn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_25/bd_8562_s02a2s_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_26/bd_8562_sawn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_27/bd_8562_swn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_28/bd_8562_sbn_1_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_29/bd_8562_m00s2a_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_30/bd_8562_m00arn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_31/bd_8562_m00rn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_32/bd_8562_m00awn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_33/bd_8562_m00wn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_34/bd_8562_m00bn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_36/bd_8562_m01s2a_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_37/bd_8562_m01arn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_38/bd_8562_m01rn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_39/bd_8562_m01awn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_40/bd_8562_m01wn_0_ooc.xdc

# XDC: bd/system/ip/system_axi_smc_2/bd_0/ip/ip_41/bd_8562_m01bn_0_ooc.xdc

# XDC: bd/system/ip/system_rst_ps7_0_10M_0/system_rst_ps7_0_10M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_10M_0 || ORIG_REF_NAME==system_rst_ps7_0_10M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps7_0_10M_0/system_rst_ps7_0_10M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_10M_0 || ORIG_REF_NAME==system_rst_ps7_0_10M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
