# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.cache/wt [current_project]
set_property parent.project_path C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/password_is_447/Desktop/image_compress/ram_system/ip_repo/apb_reg [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/Va_init.coe
add_files C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/Vn_init.coe
add_files C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/Vb_init.coe
add_files C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/Vc_init.coe
read_verilog -library xil_defaultlib {
  C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/DataRamIn.v
  C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/DataRamOut.v
  C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/GetNextSample.v
  C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/GolombCoding.v
  C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/RegularModeProcessing.v
  C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/RunModeProcessing.v
  C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/jpegls_encoder.v
  C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/imports/src/stream_concat.v
  C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/new/encoder_top.v
  C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/hdl/system_wrapper.v
}
read_ip -quiet C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/ip/ram_32x256/ram_32x256.xci
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/ip/ram_32x256/ram_32x256_ooc.xdc]

read_ip -quiet C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/ip/n_ram7x365/n_ram7x365.xci
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/ip/n_ram7x365/n_ram7x365_ooc.xdc]

read_ip -quiet C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/ip/c_ram8x365/c_ram8x365.xci
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/ip/c_ram8x365/c_ram8x365_ooc.xdc]

read_ip -quiet C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/ip/b_ram9x365/b_ram9x365.xci
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/ip/b_ram9x365/b_ram9x365_ooc.xdc]

read_ip -quiet C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/ip/a_ram13x365/a_ram13x365.xci
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/ip/a_ram13x365/a_ram13x365_ooc.xdc]

add_files C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_apb_bridge_0_0/system_axi_apb_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_1/bd_8562_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_1/bd_8562_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_2/bd_8562_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_3/bd_8562_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_4/bd_8562_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_5/bd_8562_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_6/bd_8562_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_10/bd_8562_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_11/bd_8562_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_12/bd_8562_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_13/bd_8562_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_14/bd_8562_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_15/bd_8562_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_19/bd_8562_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_20/bd_8562_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_21/bd_8562_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_25/bd_8562_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_26/bd_8562_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_27/bd_8562_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_28/bd_8562_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_29/bd_8562_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_30/bd_8562_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_31/bd_8562_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_32/bd_8562_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_33/bd_8562_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_34/bd_8562_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_36/bd_8562_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_37/bd_8562_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_38/bd_8562_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_39/bd_8562_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_40/bd_8562_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_axi_smc_2/bd_0/ip/ip_41/bd_8562_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_rst_ps7_0_10M_0/system_rst_ps7_0_10M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_rst_ps7_0_10M_0/system_rst_ps7_0_10M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/password_is_447/Desktop/image_compress/ram_system/ram_system.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_wrapper -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
